[pytest]
required_plugins = pytest-forked>=1.6
testpaths =
    src/drive_mode_manager/tests
    src/geo_pose_converter/tests
    src/gnss_lio_fusion/tests
    src/icart_bringup/tests
    src/obstacle_route_sim/tests
    src/robot_console/tools/tests
    src/robot_navigator/tests
    src/route_planner/tests
    src/route_survey/tests
    src/rtk_gps_um982/test
    src/traffic_signal_recognizer/tests
    src/tc_diagnostics/tests
norecursedirs =
    build
    install
    log
    third_party
python_files = test_*.py
