[pytest]
testpaths =
    src/drive_mode_manager/tests
    src/geo_pose_converter/tests
    src/obstacle_route_sim/tests
    src/robot_console/tools/tests
    src/route_planner/tests
    src/rtk_gps_um982/test
    src/traffic_signal_recognizer/tests
norecursedirs =
    build
    install
    log
    third_party
python_files = test_*.py
