route_planner:
  ros__parameters:
    projection_config_path: params/default.yaml
    config_yaml_path: routes/obstacle_route_sim/scurve_w3/route_config.yaml
    csv_base_dir: routes/obstacle_route_sim/scurve_w3
    map_image_path: ''
    map_worldfile_path: ''
