route_planner:
  ros__parameters:
    projection_config_path: params/default.yaml
    config_yaml_path: routes/obstacle_route_sim/straight_w2/route_config.yaml
    csv_base_dir: routes/obstacle_route_sim/straight_w2
    map_image_path: ''
    map_worldfile_path: ''
