<?xml version="1.0"?>
<package format="3">
  <name>drive_mode_manager</name>
  <version>0.1.0</version>
  <description>自律走行と手動走行の速度指令切替および専用状態表示を扱うパッケージ。</description>
  <maintainer email="kaz.ogata1988@gmail.com">kazuki</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>tc_diagnostics</depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>builtin_interfaces</exec_depend>
  <exec_depend>tc_route_msgs</exec_depend>
  <exec_depend>rtk_gps_um982_msgs</exec_depend>
  <exec_depend>joy</exec_depend>
  <exec_depend>python3-pyqt5</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
